name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    name: Backend CI
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Run backend linter
      working-directory: ./backend
      run: npm run lint --if-present
    
    - name: Run backend tests
      working-directory: ./backend
      run: npm test
    
    - name: Build backend
      working-directory: ./backend
      run: npm run build --if-present

  frontend-ci:
    runs-on: ubuntu-latest
    name: Frontend CI
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Run frontend linter
      working-directory: ./frontend
      run: npm run lint --if-present
    
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

  backend-security-audit:
    runs-on: ubuntu-latest
    name: Backend Security Audit
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Run backend security audit
      working-directory: ./backend
      run: npm audit --audit-level high

  frontend-security-audit:
    runs-on: ubuntu-latest
    name: Frontend Security Audit
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Run frontend security audit
      working-directory: ./frontend
      run: npm audit --audit-level high