name: CI - Lint, Build, Unit & Integration

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root deps
        run: npm ci

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Lint backend
        working-directory: backend
        run: npm run lint || echo "lint warnings ignored"

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint || echo "lint warnings ignored"

      - name: Build backend
        working-directory: backend
        run: npm run build

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Setup Prisma DB
        working-directory: backend
        run: npx prisma db push
        env:
          DATABASE_URL: 'file:./test.db'

      - name: Run backend unit & integration tests
        working-directory: backend
        run: npm run test:all
        env:
          DATABASE_URL: 'file:./test.db'
          JWT_SECRET: 'test-jwt-secret-key'

      - name: Run frontend unit tests
        working-directory: frontend
        run: npm run test -- --run
