name: Cypress Tests

on:
  push:
    branches: [ main, develop, 'feature/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Setup Prisma DB
        working-directory: backend
        run: npx prisma db push
        env:
          DATABASE_URL: 'file:./test.db'

      - name: Build apps
        run: npm run build

      - name: Cypress run (parallel, recorded)
        uses: cypress-io/github-action@v6
        with:
          # Start servers from repository root (backend + Vite preview)
          start: npm start
          wait-on: 'http://localhost:3001/api/health,http://localhost:4173'
          # Run Cypress pointing at the frontend project with pre-installed deps
          project: ./frontend
          install: false
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_baseUrl: http://localhost:4173
          CYPRESS_apiUrl: http://localhost:3001
