name: DEPRECATED - Comprehensive Application Testing

on:
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  DATABASE_URL: 'file:./test.db'
  JWT_SECRET: 'test-jwt-secret-key-for-ci'
  CORS_ORIGIN: 'http://localhost:5173'

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use 'CI' and 'Cypress Tests' workflows instead."