name: Live Providers E2E

on:
  workflow_dispatch:
    inputs:
      spec:
        description: 'Optional custom spec glob (defaults to live providers spec)'
        required: false
        default: 'cypress/e2e/workflow-live-providers.cy.ts'
  schedule:
    # Run daily at 07:20 UTC
    - cron: '20 7 * * *'

concurrency:
  group: live-providers-e2e-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      # These are optional. Each provider test self-skips when its key is not set.
      CYPRESS_ANTHROPIC_API_KEY: ${{ secrets.CYPRESS_ANTHROPIC_API_KEY }}
      CYPRESS_GEMINI_API_KEY: ${{ secrets.CYPRESS_GEMINI_API_KEY }}
      CYPRESS_OPENAI_API_KEY: ${{ secrets.CYPRESS_OPENAI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Live Providers spec
        run: |
          node scripts/run-e2e.js --spec "${{ github.event.inputs.spec || 'cypress/e2e/workflow-live-providers.cy.ts' }}"

      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress videos (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: frontend/cypress/videos
          if-no-files-found: ignore

      - name: Job summary
        if: always()
        run: |
          echo "Live Providers E2E completed." >> $GITHUB_STEP_SUMMARY
          echo "\nProvider keys set:" >> $GITHUB_STEP_SUMMARY
          echo "- Anthropic: $([[ -n "$CYPRESS_ANTHROPIC_API_KEY" ]] && echo set || echo not set)" >> $GITHUB_STEP_SUMMARY
          echo "- Gemini: $([[ -n "$CYPRESS_GEMINI_API_KEY" ]] && echo set || echo not set)" >> $GITHUB_STEP_SUMMARY
          echo "- OpenAI: $([[ -n "$CYPRESS_OPENAI_API_KEY" ]] && echo set || echo not set)" >> $GITHUB_STEP_SUMMARY
